## In this notebook I tried to find correlation between SalePrice and other columns

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler, PolynomialFeatures

In [4]:
df_train = pd.read_csv('./datasets/train.csv')

In [5]:
df_test = pd.read_csv('./datasets/test.csv')

In [6]:
df_train.head()

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,SalePrice
0,109,533352170,60,RL,NaN,13517,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,130500
1,544,531379050,60,RL,43.0,11492,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,4,2009,WD,220000
2,153,535304180,20,RL,68.0,7922,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,1,2010,WD,109000
3,318,916386060,60,RL,73.0,9802,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,4,2010,WD,174000
4,255,906425045,50,RL,82.0,14235,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,138500

In [7]:
df_test.head()

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type
0,2658,902301120,190,RM,69.0,9142,Pave,Grvl,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,4,2006,WD
1,2718,905108090,90,RL,NaN,9662,Pave,NaN,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,8,2006,WD
2,2414,528218130,60,RL,58.0,17104,Pave,NaN,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,9,2006,New
3,1989,902207150,30,RM,60.0,8520,Pave,NaN,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,7,2007,WD
4,625,535105100,20,RL,NaN,9500,Pave,NaN,IR1,Lvl,...,0,185,0,NaN,NaN,NaN,0,7,2009,WD

In [8]:
df_train.shape

(2051, 81)

In [9]:
df_train.isna().sum()

Id                0
PID               0
MS SubClass       0
MS Zoning         0
Lot Frontage    330
               ...
Misc Val          0
Mo Sold           0
Yr Sold           0
Sale Type         0
SalePrice         0
Length: 81, dtype: int64

In [10]:
df_train.dtypes

Id                int64
PID               int64
MS SubClass       int64
MS Zoning        object
Lot Frontage    float64
                 ...
Misc Val          int64
Mo Sold           int64
Yr Sold           int64
Sale Type        object
SalePrice         int64
Length: 81, dtype: object

In [11]:
df_train.columns[0:82]

Index(['Id', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area',
       'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities',
       'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Overall Qual',
       'Overall Cond', 'Year Built', 'Year Remod/Add', 'Roof Style',
       'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type',
       'Mas Vnr Area', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual',
       'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1',
       'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF',
       'Heating', 'Heating QC', 'Central Air', 'Electrical', '1st Flr SF',
       '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath',
       'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr',
       'Kitchen AbvGr', 'Kitchen Qual', 'TotRms AbvGrd', 'Functional',
       'Fireplaces', 'Fireplace Qu', 'Garage Type', 'Garage Yr Blt',
       'Garage Finish', 'Garage Cars', 'Garage Area', 'Garage Qual',
       'Garage Cond', 'Paved Drive', 'Wood Deck SF', 'Open Porch SF',
       'Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Pool QC',
       'Fence', 'Misc Feature', 'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type',
       'SalePrice'],
      dtype='object')

In [12]:
df_train['Exterior 1st'].value_counts()

Exterior 1st
VinylSd    724
MetalSd    331
HdBoard    300
Wd Sdng    276
Plywood    152
CemntBd     90
BrkFace     64
WdShing     45
AsbShng     33
Stucco      27
BrkComm      3
Stone        2
CBlock       2
ImStucc      1
AsphShn      1
Name: count, dtype: int64

In [13]:
df_train['Exterior 2nd'].value_counts()

Exterior 2nd
VinylSd    721
MetalSd    324
HdBoard    275
Wd Sdng    262
Plywood    185
CmentBd     90
Wd Shng     63
BrkFace     34
Stucco      30
AsbShng     28
Brk Cmn     17
ImStucc     11
Stone        6
AsphShn      3
CBlock       2
Name: count, dtype: int64

In [14]:
df_train['Exterior 1st'].dtypes

dtype('O')

In [15]:
df_train['Exterior 2nd'].dtypes

dtype('O')

In [16]:
df_train['Bldg Type'].value_counts

<bound method IndexOpsMixin.value_counts of 0       1Fam
1       1Fam
2       1Fam
3       1Fam
4       1Fam
        ...
2046    1Fam
2047    1Fam
2048    1Fam
2049    1Fam
2050    1Fam
Name: Bldg Type, Length: 2051, dtype: object>

In [17]:
df_train['Bldg Type'].dtypes

dtype('O')

In [18]:
df_train['Bldg Type'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
2046    False
2047    False
2048    False
2049    False
2050    False
Name: Bldg Type, Length: 2051, dtype: bool

In [19]:
df_new_train = df_train.drop(df_train[df_train['Bldg Type'] == 'NA'].index, inplace = True)

In [20]:
df_train.head(40)

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,SalePrice
0,109,533352170,60,RL,NaN,13517,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,130500
1,544,531379050,60,RL,43.0,11492,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,4,2009,WD,220000
2,153,535304180,20,RL,68.0,7922,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,1,2010,WD,109000
3,318,916386060,60,RL,73.0,9802,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,4,2010,WD,174000
4,255,906425045,50,RL,82.0,14235,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,138500
5,138,535126040,20,RL,137.0,16492,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,6,2010,WD,190000
6,2827,908186070,180,RM,35.0,3675,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,6,2006,New,140000
7,145,535154050,20,RL,NaN,12160,Pave,NaN,IR1,Lvl,...,0,0,NaN,MnPrv,NaN,0,5,2010,COD,142000
8,1942,535353130,20,RL,NaN,15783,Pave,NaN,Reg,Lvl,...,0,0,NaN,MnPrv,Shed,400,6,2007,WD,112500
9,1956,535426130,60,RL,70.0,11606,Pave,NaN,IR1,HLS,...,0,0,NaN,NaN,NaN,0,9,2007,WD,135000
10,1044,527451290,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,7,2008,COD,85400
11,2752,906380150,20,RL,64.0,7488,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,2,2006,WD,183600
12,807,906226060,70,RL,120.0,26400,Pave,NaN,Reg,Bnk,...,0,0,NaN,NaN,NaN,0,6,2009,WD,131000
13,1177,533236070,160,FV,24.0,2645,Pave,Pave,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,12,2008,ConLD,200000
14,1480,907418040,20,RL,74.0,9627,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,6,2008,WD,193000
15,324,923202105,20,RL,93.0,10114,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,173500
16,1311,902301140,70,RM,34.0,4571,Pave,Grvl,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,5,2008,COD,98000
17,770,905101490,20,RL,80.0,8816,Pave,NaN,Reg,Lvl,...,0,0,NaN,MnPrv,NaN,0,6,2009,WD,139000
18,2063,905107140,20,RL,71.0,8197,Pave,NaN,Reg,Lvl,...,0,0,NaN,MnPrv,NaN,0,4,2007,WD,143500
19,69,528458070,60,FV,72.0,8640,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,6,2010,Con,215200
20,2062,905106150,20,RL,109.0,8724,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,5,2007,WD,129000
21,351,527131030,120,RL,40.0,5664,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,10,2009,WD,278000
22,2393,528142010,60,RL,103.0,12867,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,7,2006,New,344133
23,12,527165230,20,RL,NaN,7980,Pave,NaN,IR1,Lvl,...,0,0,NaN,GdPrv,Shed,500,3,2010,WD,185000
24,2339,527250040,190,RL,100.0,34650,Pave,NaN,Reg,Bnk,...,0,0,NaN,NaN,NaN,0,1,2006,WD,145000
25,624,535104120,20,RL,92.0,10573,Pave,NaN,IR1,Lvl,...,288,0,NaN,GdPrv,NaN,0,4,2009,WD,187500
26,86,532376160,20,RL,65.0,8450,Pave,NaN,Reg,Lvl,...,0,0,NaN,MnPrv,NaN,0,4,2010,WD,138500
27,1534,909277040,50,RL,NaN,11700,Pave,Grvl,IR1,HLS,...,0,0,NaN,NaN,NaN,0,7,2008,WD,198000
28,2243,911103060,190,C (all),75.0,8250,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,6,2007,WD,119600
29,1957,535450190,50,RL,60.0,8064,Pave,NaN,Reg,Lvl,...,0,0,NaN,MnPrv,Shed,2000,7,2007,WD,122900
30,380,527355150,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,...,0,0,NaN,MnPrv,NaN,0,7,2009,WD,278000
31,2860,909276010,70,RL,NaN,11435,Pave,NaN,IR1,HLS,...,0,0,NaN,NaN,NaN,0,6,2006,WD,230000
32,2517,533250130,120,RL,30.0,9549,Pave,NaN,IR1,Lvl,...,216,0,NaN,NaN,NaN,0,4,2006,WD,270000
33,1933,535302070,20,RL,60.0,10950,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,4,2007,WD,125000
34,820,906340110,20,RL,79.0,10637,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,9,2009,WD,297000
35,675,535426150,20,RL,80.0,9000,Pave,NaN,IR1,HLS,...,0,0,NaN,NaN,NaN,0,4,2009,WD,113500
36,2910,923225240,160,RM,41.0,2665,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,7,2006,WD,127000
37,21,527358140,20,RL,105.0,11751,Pave,NaN,IR1,Lvl,...,0,0,NaN,MnPrv,NaN,0,1,2010,COD,190000
38,1873,534177210,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,9,2007,WD,175500
39,2125,907135050,20,RL,60.0,8428,Pave,NaN,IR2,Lvl,...,0,0,NaN,NaN,NaN,0,7,2007,WD,146000

In [21]:
df_train.tail(41)

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,SalePrice
2010,2880,911175410,30,C (all),69.0,12366,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,10,2006,WD,51689
2011,1217,534427040,20,RL,80.0,10721,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,10,2008,WD,142000
2012,1715,528172075,60,RL,92.0,10732,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,2,2007,New,250000
2013,112,534151175,60,RL,80.0,10791,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,243500
2014,454,528174070,120,RL,34.0,5122,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2009,WD,184500
2015,2253,914476330,20,RL,NaN,9928,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,5,2007,WD,210000
2016,560,532376110,20,RL,NaN,7791,Pave,NaN,IR1,Lvl,...,0,0,NaN,GdWo,NaN,0,10,2009,WD,129000
2017,303,910203250,30,RM,58.0,8154,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,4,2010,ConLw,82000
2018,1004,527161010,60,RL,100.0,10839,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,7,2008,WD,181000
2019,2167,907420110,60,RL,64.0,9045,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,6,2007,WD,167000
2020,2440,528290140,60,RL,58.0,10852,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,2,2006,WD,173000
2021,2810,907410100,60,RL,70.0,8400,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,3,2006,WD,195800
2022,2872,909475020,20,RL,NaN,16381,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,12,2006,WD,223000
2023,1072,528181010,120,RL,135.0,12304,Pave,NaN,IR3,Lvl,...,0,0,NaN,NaN,NaN,0,6,2008,WD,192000
2024,1654,527353080,60,RL,80.0,11584,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,11,2007,WD,197000
2025,2394,528142060,60,RL,82.0,10672,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,11,2006,New,298236
2026,2212,909275110,70,RL,60.0,7230,Pave,NaN,Reg,Lvl,...,153,0,NaN,GdPrv,NaN,0,10,2007,WD,238000
2027,2628,535456010,90,RL,75.0,8512,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,9,2006,WD,119000
2028,2526,534127190,20,RL,NaN,20781,Pave,NaN,IR2,Lvl,...,0,0,NaN,NaN,NaN,0,6,2006,WD,262500
2029,969,921128050,20,RL,85.0,12633,Pave,NaN,IR1,HLS,...,0,0,NaN,NaN,NaN,0,5,2009,WD,425000
2030,306,911202100,50,C (all),66.0,8712,Pave,Pave,Reg,HLS,...,0,0,NaN,NaN,NaN,0,1,2010,WD,102776
2031,25,527402250,20,RL,NaN,12537,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,4,2010,WD,149900
2032,311,914475090,80,RL,74.0,9620,Pave,NaN,Reg,Lvl,...,0,0,NaN,GdPrv,Shed,80,5,2010,WD,190000
2033,300,909455040,120,RM,35.0,3907,Pave,NaN,IR1,HLS,...,0,0,NaN,NaN,NaN,0,3,2010,WD,162500
2034,2775,907175060,20,RL,79.0,9236,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,7,2006,WD,217000
2035,2862,909279040,30,RL,80.0,11600,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,7,2006,WD,137500
2036,525,528477070,60,FV,84.0,10603,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,7,2009,WD,270000
2037,2730,905300080,20,RL,100.0,13350,Pave,NaN,IR1,Lvl,...,0,0,NaN,MnPrv,NaN,0,6,2006,WD,142500
2038,1892,534401200,80,RL,80.0,9200,Pave,NaN,Reg,Lvl,...,0,0,NaN,GdPrv,NaN,0,5,2007,WD,161000
2039,2288,923228220,160,RM,21.0,1495,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,5,2007,WD,93900
2040,2728,905225080,50,RL,81.0,15593,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,7,2006,WD,225000
2041,1065,528166120,60,RL,110.0,13688,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2008,WD,412500
2042,2842,909101080,50,RL,45.0,8248,Pave,Grvl,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,9,2006,COD,83000
2043,2011,903227140,70,RM,50.0,6000,Pave,NaN,Reg,Lvl,...,0,0,NaN,GdWo,NaN,0,2,2007,WD,128000
2044,1140,531382090,60,RL,65.0,8453,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,4,2008,WD,182000
2045,1051,528102030,20,RL,96.0,12444,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,11,2008,New,394617
2046,1587,921126030,20,RL,79.0,11449,Pave,NaN,IR1,HLS,...,0,0,NaN,NaN,NaN,0,1,2008,WD,298751
2047,785,905377130,30,RL,NaN,12342,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2009,WD,82500
2048,916,909253010,50,RL,57.0,7558,Pave,NaN,Reg,Bnk,...,0,0,NaN,NaN,NaN,0,3,2009,WD,177000
2049,639,535179160,20,RL,80.0,10400,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,11,2009,WD,144000
2050,10,527162130,60,RL,60.0,7500,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,6,2010,WD,189000

In [22]:
df_test.head()

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type
0,2658,902301120,190,RM,69.0,9142,Pave,Grvl,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,4,2006,WD
1,2718,905108090,90,RL,NaN,9662,Pave,NaN,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,8,2006,WD
2,2414,528218130,60,RL,58.0,17104,Pave,NaN,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,9,2006,New
3,1989,902207150,30,RM,60.0,8520,Pave,NaN,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,7,2007,WD
4,625,535105100,20,RL,NaN,9500,Pave,NaN,IR1,Lvl,...,0,185,0,NaN,NaN,NaN,0,7,2009,WD

In [22]:
#df_train_1 = df_train.drop(['PID', 'MS SubClass', 'MS Zoning', 'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities',
#           'Lot Config', 'Land Slope', 'Condition 1',
#           'Condition 2', 'Roof Style',
#           'Roof Matl', 'Exter Cond', 'Bsmt Qual',
#           'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1',
#           'BsmtFin Type 2', 'BsmtFin SF 2', 'Heating QC', 'Central Air', 'Electrical', 
#                                'Low Qual Fin SF', 'Gr Liv Area', 'Fireplace Qu',
#                               'Garage Yr Blt', 'Garage Finish', 'Garage Qual',
#           'Garage Cond', 'Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Pool QC',
#           'Fence', 'Misc Feature', 'Misc Val'])

In [23]:
def compute_correlation(df_train, col1, col2):

    categorized_col = df_train[col2]
    if is_object_dtype(df_train.dtypes[col2]):
        categorized_col = df_train[col2].astype('category').cat.codes
    correlation_coefficient = df_train[col1].corr(categorized_col)
    return {correlation_coefficient, col2}

In [25]:
from pandas.api.types import is_object_dtype

correlation_list = [compute_correlation(df_train,  'SalePrice', col) for col in df_train.columns]
correlation_list

[{-0.051397849884676175, 'Id'},
 {-0.2550518985277239, 'PID'},
 {-0.08733545057882373, 'MS SubClass'},
 {-0.12489936321841527, 'MS Zoning'},
 {0.34184248372687137, 'Lot Frontage'},
 {0.29656583236677875, 'Lot Area'},
 {0.0698414440180344, 'Street'},
 {-0.09741525974114496, 'Alley'},
 {-0.29975947816417164, 'Lot Shape'},
 {-0.04622394854470402, 'Land Contour'},
 {-0.036362818677354615, 'Utilities'},
 {-0.06770763024889048, 'Lot Config'},
 {0.05798984816774342, 'Land Slope'},
 {0.20774134689203894, 'Neighborhood'},
 {0.08673148994650115, 'Condition 1'},
 {0.05351250430814561, 'Condition 2'},
 {-0.04152320519895613, 'Bldg Type'},
 {0.1689835431400193, 'House Style'},
 {0.8002068702531382, 'Overall Qual'},
 {-0.09701891273609138, 'Overall Cond'},
 {0.5718488959135765, 'Year Built'},
 {0.5503696488195574, 'Year Remod/Add'},
 {0.247504317092353, 'Roof Style'},
 {0.0929731240819625, 'Roof Matl'},
 {0.1092759747968172, 'Exterior 1st'},
 {0.11374362674057456, 'Exterior 2nd'},
 {0.44338805398323616, 'Mas Vnr Type'},
 {0.5122298430253354, 'Mas Vnr Area'},
 {-0.6579392556240635, 'Exter Qual'},
 {0.12923600705186275, 'Exter Cond'},
 {0.41941670938753656, 'Foundation'},
 {-0.48110230165359974, 'Bsmt Qual'},
 {0.1529717177945905, 'Bsmt Cond'},
 {-0.21424666826022792, 'Bsmt Exposure'},
 {-0.05187598960136421, 'BsmtFin Type 1'},
 {0.42351880089988314, 'BsmtFin SF 1'},
 {0.1306073156893339, 'BsmtFin Type 2'},
 {0.016255311542868894, 'BsmtFin SF 2'},
 {0.19020974459637488, 'Bsmt Unf SF'},
 {0.6289247057344556, 'Total Bsmt SF'},
 {-0.10399543027334059, 'Heating'},
 {-0.42490944350626725, 'Heating QC'},
 {0.2773778061451661, 'Central Air'},
 {0.24466929747755584, 'Electrical'},
 {0.6184861410533948, '1st Flr SF'},
 {0.24845153013114235, '2nd Flr SF'},
 {-0.04159430329864865, 'Low Qual Fin SF'},
 {0.6970384443056634, 'Gr Liv Area'},
 {0.28366171790104505, 'Bsmt Full Bath'},
 {-0.04532773744535951, 'Bsmt Half Bath'},
 {0.5379691021121255, 'Full Bath'},
 {0.2830006979883325, 'Half Bath'},
 {0.13706693646765591, 'Bedroom AbvGr'},
 {-0.12544352246857673, 'Kitchen AbvGr'},
 {-0.6341684977577545, 'Kitchen Qual'},
 {0.5040143180735324, 'TotRms AbvGrd'},
 {0.10846023730873477, 'Functional'},
 {0.47109289376298896, 'Fireplaces'},
 {0.3896737435833162, 'Fireplace Qu'},
 {-0.2422946185041869, 'Garage Type'},
 {0.5339218965313848, 'Garage Yr Blt'},
 {-0.30865942629269144, 'Garage Finish'},
 {0.6482202649455961, 'Garage Cars'},
 {0.6502700352166243, 'Garage Area'},
 {0.26802995818398556, 'Garage Qual'},
 {0.2706572311405732, 'Garage Cond'},
 {0.29047215802091186, 'Paved Drive'},
 {0.3264897021896559, 'Wood Deck SF'},
 {0.3334760297920544, 'Open Porch SF'},
 {-0.13565649182472103, 'Enclosed Porch'},
 {0.04873185398349617, '3Ssn Porch'},
 {0.13458135196225846, 'Screen Porch'},
 {0.02310631715788679, 'Pool Area'},
 {0.011778508347572951, 'Pool QC'},
 {-0.18997419499489218, 'Fence'},
 {-0.046681403493412085, 'Misc Feature'},
 {-0.007374759586406777, 'Misc Val'},
 {0.03273540854904898, 'Mo Sold'},
 {-0.015203224433671371, 'Yr Sold'},
 {-0.015645938655583082, 'Sale Type'},
 {0.9999999999999998, 'SalePrice'}]

In [26]:
positive_corr_list = [{k,v} for k,v in correlation_list if isinstance(k, (int, float)) and float(k) > 0]
positive_corr_list

[{0.34184248372687137, 'Lot Frontage'},
 {0.29656583236677875, 'Lot Area'},
 {0.0698414440180344, 'Street'},
 {0.05798984816774342, 'Land Slope'},
 {0.20774134689203894, 'Neighborhood'},
 {0.08673148994650115, 'Condition 1'},
 {0.05351250430814561, 'Condition 2'},
 {0.1689835431400193, 'House Style'},
 {0.8002068702531382, 'Overall Qual'},
 {0.5718488959135765, 'Year Built'},
 {0.5503696488195574, 'Year Remod/Add'},
 {0.247504317092353, 'Roof Style'},
 {0.0929731240819625, 'Roof Matl'},
 {0.1092759747968172, 'Exterior 1st'},
 {0.11374362674057456, 'Exterior 2nd'},
 {0.44338805398323616, 'Mas Vnr Type'},
 {0.5122298430253354, 'Mas Vnr Area'},
 {0.12923600705186275, 'Exter Cond'},
 {0.41941670938753656, 'Foundation'},
 {0.1529717177945905, 'Bsmt Cond'},
 {0.42351880089988314, 'BsmtFin SF 1'},
 {0.1306073156893339, 'BsmtFin Type 2'},
 {0.016255311542868894, 'BsmtFin SF 2'},
 {0.19020974459637488, 'Bsmt Unf SF'},
 {0.6289247057344556, 'Total Bsmt SF'},
 {0.2773778061451661, 'Central Air'},
 {0.24466929747755584, 'Electrical'},
 {0.6184861410533948, '1st Flr SF'},
 {0.24845153013114235, '2nd Flr SF'},
 {0.6970384443056634, 'Gr Liv Area'},
 {0.28366171790104505, 'Bsmt Full Bath'},
 {0.5379691021121255, 'Full Bath'},
 {0.2830006979883325, 'Half Bath'},
 {0.13706693646765591, 'Bedroom AbvGr'},
 {0.5040143180735324, 'TotRms AbvGrd'},
 {0.10846023730873477, 'Functional'},
 {0.47109289376298896, 'Fireplaces'},
 {0.3896737435833162, 'Fireplace Qu'},
 {0.5339218965313848, 'Garage Yr Blt'},
 {0.6482202649455961, 'Garage Cars'},
 {0.6502700352166243, 'Garage Area'},
 {0.26802995818398556, 'Garage Qual'},
 {0.2706572311405732, 'Garage Cond'},
 {0.29047215802091186, 'Paved Drive'},
 {0.3264897021896559, 'Wood Deck SF'},
 {0.3334760297920544, 'Open Porch SF'},
 {0.04873185398349617, '3Ssn Porch'},
 {0.13458135196225846, 'Screen Porch'},
 {0.02310631715788679, 'Pool Area'},
 {0.03273540854904898, 'Mo Sold'},
 {0.9999999999999998, 'SalePrice'}]

In [ ]:
# 'MS SubClass','Alley','Land Contour', 'Utilities', 'Lot Config'
# 'Bldg Type', 'Overall Cond', 'BsmtFin Type 1', 'Low Qual Fin SF'
# 'Bsmt Half Bath', 'Misc Feature', 'Yr Sold', 'Sale Type'

In [27]:
negative_corr_list = [{k,v} for k,v in correlation_list if isinstance(k, (int, float)) and float(k) < 0]
negative_corr_list

[{-0.051397849884676175, 'Id'},
 {-0.2550518985277239, 'PID'},
 {-0.08733545057882373, 'MS SubClass'},
 {-0.12489936321841527, 'MS Zoning'},
 {-0.09741525974114496, 'Alley'},
 {-0.29975947816417164, 'Lot Shape'},
 {-0.04622394854470402, 'Land Contour'},
 {-0.036362818677354615, 'Utilities'},
 {-0.06770763024889048, 'Lot Config'},
 {-0.04152320519895613, 'Bldg Type'},
 {-0.09701891273609138, 'Overall Cond'},
 {-0.6579392556240635, 'Exter Qual'},
 {-0.48110230165359974, 'Bsmt Qual'},
 {-0.21424666826022792, 'Bsmt Exposure'},
 {-0.05187598960136421, 'BsmtFin Type 1'},
 {-0.10399543027334059, 'Heating'},
 {-0.42490944350626725, 'Heating QC'},
 {-0.04159430329864865, 'Low Qual Fin SF'},
 {-0.04532773744535951, 'Bsmt Half Bath'},
 {-0.12544352246857673, 'Kitchen AbvGr'},
 {-0.6341684977577545, 'Kitchen Qual'},
 {-0.2422946185041869, 'Garage Type'},
 {-0.30865942629269144, 'Garage Finish'},
 {-0.13565649182472103, 'Enclosed Porch'},
 {-0.18997419499489218, 'Fence'},
 {-0.046681403493412085, 'Misc Feature'},
 {-0.015203224433671371, 'Yr Sold'},
 {-0.015645938655583082, 'Sale Type'}]

In [28]:
negative_corr_list_name = [ v for k,v in correlation_list if isinstance(k, (int, float)) and float(k) < 0]
negative_corr_list_name

['Id',
 'PID',
 'MS SubClass',
 'MS Zoning',
 'Alley',
 'Lot Shape',
 'Land Contour',
 'Utilities',
 'Lot Config',
 'Bldg Type',
 'Overall Cond',
 'Exter Qual',
 'Bsmt Qual',
 'Bsmt Exposure',
 'BsmtFin Type 1',
 'Heating',
 'Heating QC',
 'Low Qual Fin SF',
 'Bsmt Half Bath',
 'Kitchen AbvGr',
 'Kitchen Qual',
 'Garage Type',
 'Garage Finish',
 'Enclosed Porch',
 'Fence',
 'Misc Feature',
 'Yr Sold',
 'Sale Type']

In [29]:
df_train.head

<bound method NDFrame.head of         Id        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street  \
0      109  533352170           60        RL           NaN     13517   Pave
1      544  531379050           60        RL          43.0     11492   Pave
2      153  535304180           20        RL          68.0      7922   Pave
3      318  916386060           60        RL          73.0      9802   Pave
4      255  906425045           50        RL          82.0     14235   Pave
...    ...        ...          ...       ...           ...       ...    ...
2046  1587  921126030           20        RL          79.0     11449   Pave
2047   785  905377130           30        RL           NaN     12342   Pave
2048   916  909253010           50        RL          57.0      7558   Pave
2049   639  535179160           20        RL          80.0     10400   Pave
2050    10  527162130           60        RL          60.0      7500   Pave

     Alley Lot Shape Land Contour  ... Screen Porch Pool Area Pool QC Fence  \
0      NaN       IR1          Lvl  ...            0         0     NaN   NaN
1      NaN       IR1          Lvl  ...            0         0     NaN   NaN
2      NaN       Reg          Lvl  ...            0         0     NaN   NaN
3      NaN       Reg          Lvl  ...            0         0     NaN   NaN
4      NaN       IR1          Lvl  ...            0         0     NaN   NaN
...    ...       ...          ...  ...          ...       ...     ...   ...
2046   NaN       IR1          HLS  ...            0         0     NaN   NaN
2047   NaN       IR1          Lvl  ...            0         0     NaN   NaN
2048   NaN       Reg          Bnk  ...            0         0     NaN   NaN
2049   NaN       Reg          Lvl  ...            0         0     NaN   NaN
2050   NaN       Reg          Lvl  ...            0         0     NaN   NaN

     Misc Feature Misc Val Mo Sold Yr Sold  Sale Type  SalePrice
0             NaN        0       3    2010        WD      130500
1             NaN        0       4    2009        WD      220000
2             NaN        0       1    2010        WD      109000
3             NaN        0       4    2010        WD      174000
4             NaN        0       3    2010        WD      138500
...           ...      ...     ...     ...        ...        ...
2046          NaN        0       1    2008        WD      298751
2047          NaN        0       3    2009        WD       82500
2048          NaN        0       3    2009        WD      177000
2049          NaN        0      11    2009        WD      144000
2050          NaN        0       6    2010        WD      189000

[2051 rows x 81 columns]>

In [28]:
#I have not included ID in drop list as we need that

In [34]:
df_train_1 = df_train.drop(columns = ['MS SubClass','Alley','Land Contour', 'Utilities', 'Lot Config',
                    'Bldg Type', 'Overall Cond', 'BsmtFin Type 1', 'Low Qual Fin SF',
                    'Bsmt Half Bath', 'Misc Feature', 'Yr Sold', 'Sale Type'])

In [35]:
df_train_1

,Id,PID,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Slope,Neighborhood,Condition 1,...,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Val,Mo Sold,SalePrice
0,109,533352170,RL,NaN,13517,Pave,IR1,Gtl,Sawyer,RRAe,...,44,0,0,0,0,NaN,NaN,0,3,130500
1,544,531379050,RL,43.0,11492,Pave,IR1,Gtl,SawyerW,Norm,...,74,0,0,0,0,NaN,NaN,0,4,220000
2,153,535304180,RL,68.0,7922,Pave,Reg,Gtl,NAmes,Norm,...,52,0,0,0,0,NaN,NaN,0,1,109000
3,318,916386060,RL,73.0,9802,Pave,Reg,Gtl,Timber,Norm,...,0,0,0,0,0,NaN,NaN,0,4,174000
4,255,906425045,RL,82.0,14235,Pave,IR1,Gtl,SawyerW,Norm,...,59,0,0,0,0,NaN,NaN,0,3,138500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2046,1587,921126030,RL,79.0,11449,Pave,IR1,Gtl,Timber,Norm,...,276,0,0,0,0,NaN,NaN,0,1,298751
2047,785,905377130,RL,NaN,12342,Pave,IR1,Gtl,Edwards,Norm,...,0,0,0,0,0,NaN,NaN,0,3,82500
2048,916,909253010,RL,57.0,7558,Pave,Reg,Gtl,Crawfor,Norm,...,0,0,0,0,0,NaN,NaN,0,3,177000
2049,639,535179160,RL,80.0,10400,Pave,Reg,Gtl,NAmes,Norm,...,189,140,0,0,0,NaN,NaN,0,11,144000
2050,10,527162130,RL,60.0,7500,Pave,Reg,Gtl,Gilbert,Norm,...,60,0,0,0,0,NaN,NaN,0,6,189000

In [36]:
df_train_1.to_csv(".cleaned_data.csv",index=False)